//Produced by slp2pov v2.0
//Extents of : ALTER_FLOWER_STAND 
//     Min : <   -6.419,    0.000,   -6.419 >
//     Max : <    6.419,   50.327,    6.419 >
//     Triangle Count : 8200

#declare COLOR_0 = texture { pigment { color red 0.950 green 0.930 blue 0.930 }}
#declare COLOR_1 = texture { pigment { color red 0.410 green 0.262 blue 0.113 }}
#declare COLOR_2 = texture { pigment { color red 0.804 green 0.588 blue 0.196 }}
#declare COLOR_3 = texture { pigment { color red 1.000 green 1.000 blue 1.000 }}

#declare ALTER_FLOWER_STAND = union {
box {<-6.419281,0.000000,-6.419281>,<6.419281,50.326950,6.419281>}
texture { COLOR_0 }
}
