//Produced by slp2pov v2.0
//Extents of : BREAD_BASKET 
//     Min : <   -6.054,   -0.029,   -5.962 >
//     Max : <    6.054,    4.446,    5.962 >
//     Triangle Count : 54490

#declare COLOR_0 = texture { pigment { color red 0.410 green 0.262 blue 0.113 }}
#declare COLOR_1 = texture { pigment { color red 1.000 green 1.000 blue 0.949 }}
#declare COLOR_2 = texture { pigment { color red 1.000 green 0.808 blue 0.498 }}

#declare BREAD_BASKET = union {
box {<-6.053869,-0.029019,-5.961940>,<6.053869,4.446215,5.961897>}
texture { COLOR_0 }
}
