//Produced by slp2pov v2.0
//Extents of : LECTURN_MIC 
//     Min : <   12.852,    3.959,    4.872 >
//     Max : <   14.494,    5.208,    5.749 >
//     Triangle Count : 1858

#declare COLOR_0 = texture { pigment { color red 0.669 green 0.670 blue 0.655 }}
#declare COLOR_1 = texture { pigment { color red 0.420 green 0.420 blue 0.420 }}
#declare COLOR_2 = texture { pigment { color red 0.130 green 0.130 blue 0.140 }}

#declare LECTURN_MIC = union {
box {<12.852380,3.958856,4.872051>,<14.493820,5.208405,5.748945>}
texture { COLOR_0 }
}
