//Produced by slp2pov v2.0
//Extents of : BIBLE 
//     Min : <   -6.354,    0.000,  -13.992 >
//     Max : <    8.629,   10.755,   13.992 >
//     Triangle Count : 20152

#declare COLOR_0 = texture { pigment { color red 0.432 green 0.227 blue 0.042 }}
#declare COLOR_1 = texture { pigment { color red 0.824 green 0.706 blue 0.431 }}
#declare COLOR_2 = texture { pigment { color red 1.000 green 1.000 blue 1.000 }}

#declare BIBLE = union {
box {<-6.354367,0.000000,-13.991630>,<8.628835,10.754870,13.991630>}
texture { COLOR_0 }
}
