//Produced by slp2pov v2.0
//Extents of : PEW1 
//     Min : <  -18.500,    0.000, -101.500 >
//     Max : <    1.974,   35.701,  101.500 >
//     Triangle Count : 2888

#declare COLOR_0 = texture { pigment { color red 1.000 green 1.000 blue 1.000 }}
#declare COLOR_1 = texture { pigment { color red 0.800 green 0.501 blue 0.260 }}
#declare COLOR_2 = texture { pigment { color red 0.380 green 0.238 blue 0.124 }}

#declare PEW1 = union {
box {<-18.500000,0.000000,-101.500000>,<1.973920,35.701410,101.500000>}
texture { COLOR_0 }
}
