//Produced by slp2pov v2.0
//Extents of : LECTURN 
//     Min : <   -9.965,    0.000,  -11.168 >
//     Max : <    9.352,   48.373,   11.168 >
//     Triangle Count : 1732

#declare COLOR_0 = texture { pigment { color red 0.950 green 0.930 blue 0.930 }}
#declare COLOR_1 = texture { pigment { color red 0.410 green 0.262 blue 0.113 }}

#declare LECTURN = union {
box {<-9.964819,0.000000,-11.168280>,<9.352037,48.373120,11.168250>}
texture { COLOR_0 }
}
