//Produced by slp2pov v2.0
//Extents of : PENCIL 
//     Min : <   -0.190,    0.000,   -0.190 >
//     Max : <    0.190,    8.671,    0.190 >
//     Triangle Count : 13982

#declare COLOR_0 = texture { pigment { color red 0.925 green 0.443 blue 0.184 }}
#declare COLOR_1 = texture { pigment { color red 1.000 green 1.000 blue 1.000 }}
#declare COLOR_2 = texture { pigment { color red 1.000 green 0.808 blue 0.498 }}

#declare PENCIL = union {
box {<-0.189857,0.000000,-0.189857>,<0.189857,8.671121,0.189857>}
texture { COLOR_0 }
}
