//Produced by slp2pov v2.0
//Extents of : ALTER 
//     Min : <  -33.481,    0.000,  -12.250 >
//     Max : <   33.481,   34.500,   12.481 >
//     Triangle Count : 3860

#declare COLOR_0 = texture { pigment { color red 0.950 green 0.930 blue 0.930 }}
#declare COLOR_1 = texture { pigment { color red 0.410 green 0.262 blue 0.113 }}

#declare ALTER = union {
box {<-33.480820,0.000000,-12.250000>,<33.480860,34.500000,12.480860>}
texture { COLOR_0 }
}
