//Produced by slp2pov v2.0
//Extents of : BAPTISM_FONT 
//     Min : <  -13.498,    0.000,  -13.498 >
//     Max : <   13.498,   47.000,   13.498 >
//     Triangle Count : 18900

#declare COLOR_0 = texture { pigment { color red 0.410 green 0.262 blue 0.113 }}
#declare COLOR_1 = texture { pigment { color red 1.000 green 1.000 blue 0.949 }}

#declare BAPTISM_FONT = union {
box {<-13.498290,0.000000,-13.498290>,<13.498290,47.000000,13.498290>}
texture { COLOR_0 }
}
