//Produced by slp2pov v2.0
//Extents of : CHALICE 
//     Min : <   -2.799,    0.000,   -2.913 >
//     Max : <    2.759,    8.089,    2.943 >
//     Triangle Count : 17522

#declare COLOR_0 = texture { pigment { color red 0.927 green 0.414 blue 0.139 }}
#declare COLOR_1 = texture { pigment { color red 0.680 green 0.000 blue 0.480 }}
#declare COLOR_2 = texture { pigment { color red 0.695 green 0.743 blue 0.790 }}

#declare CHALICE = union {
box {<-2.799211,0.000000,-2.913380>,<2.758508,8.089198,2.943192>}
texture { COLOR_0 }
}
